### ISSUE TITLE
State dependency on libmagic

### ISSUE THREAD

**Issue by jimrybarski** [rabite0/hunter#3]
Compilation on Xubuntu 18.04 failed due to a missing library:

```
= note: /usr/bin/ld: cannot find -lmagic
       collect2: error: ld returned 1 exit status
```

Installing the `libmagic-dev` package allowed compilation to succeed. I suggest putting all the non-Rust dependencies in the readme.

**Comment by steveslatky** [comment]
Yup, solved it for me. 

@rabite0 You mind if I submit a pull request to add to the readme for a short installation guide?

**Comment by rabite0** [comment]
Thanks for reporting. Quite unfortunate, since right now it's actually only used to check if a file is plain text. Not sure if it's possible to check for that easily, though.

@steveslatky No, I'm actually quite happy that people want to help out, so feel free to do so.

**Comment by mfornet** [comment]
I added symlink `libmagic.so.1` to `libmagic.so`.
From this answer in [stackoverlfow](https://stackoverflow.com/a/335958/4950797).

**Comment by rabite0** [comment]
Is this resolved? I'm not sure...

**Comment by rabite0** [comment]
If there is more that can be done about this, feel free to reopen.
