### ISSUE TITLE
#![feature] may not be used on the stable release channel

### ISSUE THREAD

**Issue by Dentrax** [rabite0/hunter#30]
Hey,

Thank for the project! You are doing well. :)

On compiling phase via `AUR` on Arch Linux, I am getting this:

```
error[E0554]: #![feature] may not be used on the stable release channel
 --> /home/dentrax/.cargo/registry/src/github.com-1ecc6299db9ec823/hunter-1.1.0/src/main.rs:1:1
  |
1 | #![feature(vec_remove_item)]
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0554]: #![feature] may not be used on the stable release channel
 --> /home/dentrax/.cargo/registry/src/github.com-1ecc6299db9ec823/hunter-1.1.0/src/main.rs:2:1
  |
2 | #![feature(trivial_bounds)]
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0554]: #![feature] may not be used on the stable release channel
 --> /home/dentrax/.cargo/registry/src/github.com-1ecc6299db9ec823/hunter-1.1.0/src/main.rs:3:1
  |
3 | #![feature(try_trait)]
  | ^^^^^^^^^^^^^^^^^^^^^^

error[E0554]: #![feature] may not be used on the stable release channel
 --> /home/dentrax/.cargo/registry/src/github.com-1ecc6299db9ec823/hunter-1.1.0/src/main.rs:4:1
  |
4 | #![feature(fnbox)]
  | ^^^^^^^^^^^^^^^^^^

error: aborting due to 4 previous errors

For more information about this error, try `rustc --explain E0554`.
error: failed to compile `hunter v1.1.0`, intermediate artifacts can be found at `/tmp/cargo-installTlPHje`
```

Similar to: #15 

But, I am new to Rust; So, I don't exactly understand the Rust specific terms. How could we solve the this bug (with box-of-the-box way)?

cargo: `cargo 1.34.0`
rustc: `rustc 1.34.0`

Thanks!

**Comment by straussdd** [comment]
This happens because `hunter` uses features of the Rust library which haven't been finalized yet. These features can only be compiled using `rustc` compilers from the "nightly" release channel. You can get them by using Rustup (https://rustup.rs/) and selecting the nightly channel when asked.

There's already ongoing work to get hunter running on the stable release channel as well (see #15), but this effort probably will have to wait for the completion of the `try_trait` feature from rust-lang/rust#42327.

**Comment by straussdd** [comment]
I've re-read the README.md and noticed that it makes no mention of the nightly branch being a requirement. This should definitely be changed to allow for successful compilation without prior knowledge of Rust toolchain internals.

@rabite0: Maybe add rustup + nightly as installation steps in README.md, so this bug won't pop up again?

**Comment by rabite0** [comment]
I added a note about rustup. Soon there will be binary packages, so installation should become a non-issue.
