### ISSUE TITLE
How to exit Hunter?

### ISSUE THREAD

**Issue by Mart-Bogdan** [rabite0/hunter#31]
I pressed something (wanted to type ls, forgot htat hunter is open)
and now it shows it's log and I can't exit
![image](https://user-images.githubusercontent.com/775038/57090167-d6123d00-6d0e-11e9-92e0-3ec43950d548.png)

**Comment by rabite0** [comment]
q quits hunter, but it only works in the main view. To get out of the log view press g (or l with holy bindings).

**Comment by Mart-Bogdan** [comment]
Thanks. for information, what key is to get to log viewer?

**Comment by Mart-Bogdan** [comment]
Got it  -- `l`

**Comment by rabite0** [comment]
It should be g as well, unless you're using the holy-branch, then it's l.

**Comment by Mart-Bogdan** [comment]
dunno what's holly branch, I've just made `cargo install hunter` :-)
