### ISSUE TITLE
Bulk Rename

### ISSUE THREAD

**Issue by CoolOppo** [rabite0/hunter#36]
Bulk renaming is the only thing stopping me from never using Ranger.

https://github.com/ranger/ranger/wiki/Official-user-guide#bulk-renaming

**Comment by rabite0** [comment]
Seems like you can do that with qmv from  renameutils: https://www.nongnu.org/renameutils/

Here's a nice demonstration with pictures. Look for method 3: https://www.ostechnix.com/how-to-rename-multiple-files-at-once-in-linux/

Seems like it does exactly what you want.

**Comment by CoolOppo** [comment]
Alright I guess I will make it in rust

**Comment by CoolOppo** [comment]
All done. https://github.com/CoolOppo/bren

**Comment by rabite0** [comment]
Cool! Good job!
