### ISSUE TITLE
Add IRC channel

### ISSUE THREAD

**Issue by alexherbo2** [rabite0/hunter#39]

**Comment by rabite0** [comment]
Sounds interesting. I'm in #hunter on freenode. It seems to be owned by some freenode bot or something, but it's abandoned and empty. I will talk to someone from freenode, maybe they could transfer ownership to me.

**Comment by rabite0** [comment]
#hunter on freenode is the official hunter chanel. Will update the README soon.

**Comment by rabite0** [comment]
Official IRC channel established.

https://github.com/rabite0/hunter/commit/4a40754c4a18392edfa7ce0e0f9a1a33bb0d6fde
