### ISSUE TITLE
Compilation error: missing feature uniform_paths

### ISSUE THREAD

**Issue by cout970** [rabite0/hunter#4]
Compiling the version 1.0.1 in Manjaro I got 5 compiling errors like this:
```
error[E0658]: imports can only refer to extern crate names passed with `--extern` on stable channel (see issue #53130)
  --> src/main.rs:62:5
   |
41 | mod tabview;
   | ------------ not an extern crate passed with `--extern`
...
62 | use tabview::TabView;
   |     ^^^^^^^
   |
   = help: add #![feature(uniform_paths)] to the crate attributes to enable
```
Command used: `cargo build --release`
Workaround: adding `#![feature(uniform_paths)]` at the start of main.rs makes the project compile.

**Comment by rabite0** [comment]
Are you using an older nightly compiler by any chance? When I added that flag it says that this has actually been stable since rust 1.32.

**Comment by rabite0** [comment]
Added rust-toolchain so it will automatically use a sufficient rust compiler. That should fix this.
