### ISSUE TITLE
Add batch_cmd option

### ISSUE THREAD

**Issue by alexherbo2** [rabite0/hunter#40]
How about adding a `batch_cmd` option to batch rename / delete – and more generally, for batch processing – a set of selections?

**Example** – Batch processing with [Batch]:

`~/.config/hunter/config`

```
batch_cmd=batch
```

[Batch]: https://github.com/alexherbo2/batch

**Comment by rabite0** [comment]
You can select multiple files call "batch $s" right now. Is there something missing?

**Comment by rabite0** [comment]
You can do this with the normal command runner (type "!"). It just runs whatever you type in a $SHELL. Either run 

```for file in s; do cat $file; done```

or use xargs:

```echo $s | xargs cat```

You could even write a script if you do this often and want do type less. If you append "!" to the command it will also run in the foreground, so you can run your batch command with this, too.
