### ISSUE TITLE
Quoted list values

### ISSUE THREAD

**Issue by alexherbo2** [rabite0/hunter#43]
Use the same approach than [Kakoune][Kakoune – Expansions].

**Example** – Print selected files:

``` sh
eval "set -- $s"

# Using a for-loop
for file do
  echo "$file"
done

# Using printf
printf '%s\n' "$@"
```

[Kakoune – Expansions]: https://github.com/mawww/kakoune/blob/master/doc/pages/expansions.asciidoc

**Comment by rabite0** [comment]
Double-quotes in file names need to be escaped to work correctly, need to do that.
I'm not sure about what you're asking for, there is no scripting language in hunter, it's using $SHELL for everything.

**Comment by rabite0** [comment]
Quotes in file names are fixed now. I tested with all kinds of crap like ```foo'"bar$'b '" baz```
(single file name) and it was working fine where it broke before.
