### ISSUE TITLE
Rename --show-hidden command-line option

### ISSUE THREAD

**Issue by alexherbo2** [rabite0/hunter#50]
- Rename `--show-hidden` → `--all`
- Rename `-h` → `-a`
- Add `-h` for help

**Comment by rabite0** [comment]
I was almost done with this, but then I realized I forgot abut the "-a" switch. It's already used to disable animations. I'm not sure what switch to use for that. I thought about "-s" for static or something, but it's just not as intuitive.

So I'm not sure what to do about this. There are many programs that use "-h" for something other than help. I don't think it's a big deal.
