### ISSUE TITLE
Expose selections in the argument list

### ISSUE THREAD

**Issue by alexherbo2** [rabite0/hunter#53]

**Comment by rabite0** [comment]
You mean instead of "$s"?

That's only in the minibuffer when entering a command, the reason is that it gets messy when you have many files selected. In the process viewer you see the full command with the file names, also when you get a notification when the process quits in the status bar.

**Comment by rabite0** [comment]
Please clarify.

**Comment by rabite0** [comment]
There's a file selection filter now (Alt-v).
