### ISSUE TITLE
(FEATURE REQUEST)Devicons Built-In

### ISSUE THREAD

**Issue by gottaStartNow** [rabite0/hunter#55]
Would be really cool if Hunter had devicons built in. Here is an example of what I mean, [https://github.com/alexanderjeurissen/ranger_devicons](Ranger Devicons) .

**Comment by rabite0** [comment]
Have you tried in ```~/.config/hunter/config```
```icons=on```
Does that work?

**Comment by gottaStartNow** [comment]
Just switched to Manjaro and it was a Ubuntu problem. With your permission may I rewrite the docs and create a wiki for clarity?

**Comment by rabite0** [comment]
Sure, that would be great!

**Comment by gottaStartNow** [comment]
Wonderful I will do a pull request soon and we can keep the conversation there or by email if you prefer.

**Comment by rabite0** [comment]
On Github is fine for me.
