### ISSUE TITLE
Check rust compiler version

### ISSUE THREAD

**Issue by rabite0** [rabite0/hunter#57]
A lot of people had problems compiling hunter, because they weren't using a recent enough nightly compiler. 

Solution:
A check in build.rs and bail with a warning when they're not on rust-nightly.

**Comment by gottaStartNow** [comment]
https://stackoverflow.com/questions/49247618/check-whether-compiler-is-nightly-at-compile-time this would be a good starting point I think

**Comment by rabite0** [comment]
Cool, thanks.
