### ISSUE TITLE
Add to Homebrew

### ISSUE THREAD

**Issue by andrewbanchich** [rabite0/hunter#61]
Any chance you could add this to [Homebrew](https://brew.sh/)?

**Comment by rabite0** [comment]
Not likely at the moment. If you want to install from source, I would suggest just using cargo. If you want binaries, there will be new releases soon here: https://github.com/rabite0/hunter/releases

Currently the build bot is still not working, but I already fixed the main problem, so I'll probably get to it soon.

I don't really want to get into maintaining tons of different distribution channels. If someone else wants to do it and/or it can be automated, that would be fine though.
