### ISSUE TITLE
README 

### ISSUE THREAD

**Issue by ghuls** [rabite0/hunter#64]
> PREVIEWERS
> 
> hunter comes with definitions to enable previewing certain file **typse**. To use this you need to install some programs first. You can also define your own. See below. Defaults are:
> 
>     bat / highlight for syntax highlighting
>     7z for archives
>     w3m / links / elinks / lynx for html
>     pdftotext / mutool for pdf
> 
> Debian/Ubuntu
> 
>     **apt install gcc libmagic-dev gstreamer1.0-devel gst-plugins-base gst-plugins-good**

Fix typo: `typse` ==> `types`

The installation dependencies are not for Debian/Ubuntu.

This works for me (Ubuntu 18.04):

`apt-get gcc libgstreamer-plugins-base1.0-dev gstreamer1.0-plugins-good`

`libmagic.so` is provided by `libmagic1` package, but I have the feeling it is not required anymore by hunter as `tree_magic` is now used instead of `mime_detective`.

**Comment by ghuls** [comment]
From commit https://github.com/rabite0/hunter/commit/072b39b3cfeac109f8bb0fff747c6dc50d747942, the following is also needed for `hunter-media`
`apt-get install libsixel-bin`

**Comment by rabite0** [comment]
Thanks for pointing out the typo and the list of dependencies. I will update the README soon. 

And yes, I haven't yet added any info about SIXEL/kitty yet, mostly because it's not completely done and I'm still working on parts of it.

**Comment by ghuls** [comment]
The `gstreamer-player-sys` crate requires `gstreamer-player-1.0` which is provided by `libgstreamer-plugins-bad1.0-dev`.

I think this are all the needed dependencies:
```
apt-get gcc libgstreamer-plugins-base1.0-dev gstreamer1.0-plugins-good libgstreamer-plugins-bad1.0-dev libsixel-bin
```

**Comment by rabite0** [comment]
Thanks, just added this to the README.

Note that sixel is optional, if you don't want it you can disable it.
