### ISSUE TITLE
Hunter output breaks if the terminal is too wide.

### ISSUE THREAD

**Issue by ghuls** [rabite0/hunter#65]
Hunter output breaks if the terminal is too wide. It seems to happen when there are more than 197 columns in the terminal.

It only show a line on the first row and on the bottom row.

It happens both in `gnome-terminal` and `alacritty`.

```
# Terminal width
$ tput cols
197
```

**Comment by rabite0** [comment]
Crap, I messed up a manual merge there with the last update. It's fixed for now. Thanks, wouldn't have noticed.
