### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by d4h0** [rabite0/hunter#73]
Hi,

It seems several new features are not included in the last release from last July.

I couldn't get image previews working until I installed the [dev version of hunter from my package manager](https://aur.archlinux.org/packages/hunter-git/). The -u option also wasn't available.

**Comment by rabite0** [comment]
Could be, it seems like I forgot to push a few of the tags that mark the releases to the repo. I just made a new release with all that stuff and a few new bugfixes.
