### ISSUE TITLE
Icons are not displayed correctly 

### ISSUE THREAD

**Issue by snpefk** [rabite0/hunter#79]
Hi. 
Thanks for your work (and beautiful preview in README). I'm experience incorrect display of icons with `FuraCode` font (from NerdFonts), here is screenshot
![hunter-icons](https://user-images.githubusercontent.com/2883201/74691175-d1ae0680-51f2-11ea-9106-c296aaf4a4a7.png)
and the same font in `lf` 
![lf-icons](https://user-images.githubusercontent.com/2883201/74691123-9a3f5a00-51f2-11ea-8af8-c4c7fe86388e.png)

**Comment by rabite0** [comment]
This looks like the icons are rendered wrong and too big to fit into grid. This is either a configuration problem or a bug in terminal or some other piece of software that handles font rendering. Maybe even a bug in the font itself.

That said, I *could* add a workaround for this. The way it looks lf draws a space after the icon, whereas hunter doesn't (I did this to leave more space for the file name).

**Comment by rabite0** [comment]
Done, You can not set an option "icons_space=on" in ~/.config/hunter/config and it will put a space between the icon and the file name. I like the "condensed" look, but some might prefer the space. I've been thinking about adding this, but so far no one complained ;).

**Comment by snpefk** [comment]
Cool, works as expected. Thanks!
